# -*- coding: utf-8 -*-
"""data_prep.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Nw7zkE2YQjSNwo6QBcVozYirYqTnACQu
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import os

raw_path = '/content/drive/MyDrive/f1_mlops/data/raw/'
processed_path = '/content/drive/MyDrive/f1_mlops/data/processed/'

df_results = pd.read_csv(f'{raw_path}results.csv')
df_races = pd.read_csv(f'{raw_path}races.csv')
df_drivers = pd.read_csv(f'{raw_path}drivers.csv')
df_constructors = pd.read_csv(f'{raw_path}constructors.csv')

df_m1 = pd.merge(df_results, df_races, on='raceId', how='left')

df_m2 = pd.merge(df_m1, df_drivers, on='driverId', how='left')

df_final = pd.merge(df_m2, df_constructors, on='constructorId', how='left')

columnas_utiles = [
    'year',                 # Año
    'name_x',               # Nombre del Gran Premio
    'driverRef',            # Identificador del piloto
    'constructorRef',       # Identificador de la escudería (¡NUEVO!)
    'grid',                 # Posición de salida
    'positionOrder',        # Posición final en carrera
    'points',               # Puntos conseguidos
    'statusId'              # Si terminó o abandonó
]

df_limpio = df_final[columnas_utiles].copy()

df_limpio.rename(columns={'name_x': 'gp_name'}, inplace=True)

os.makedirs(processed_path, exist_ok=True)
output_file = f'{processed_path}f1_dataset_clean.csv'
df_limpio.to_csv(output_file, index=False)

print(df_limpio.head())
